version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/minio/health/live || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
  minio-data:
