package main

import (
	"context"
	"log"

	// docs is generated by Swag CLI, you have to import it.

	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "rsp/docs"
)

func init() {
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}
}

// export POSTGRESQL_URL='postgres://root:1234@localhost:5432/db?sslmode=disable'
// migrate create -ext sql -dir db/migrations -seq create_product_table
// migrate -path db/migrations/ -database $POSTGRESQL_URL up

// @title           twp API
// @version         0.o
// @description     twp server api.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/

func main() {
	CheckBuckets(context.Background())
	e := echo.New()
	e.Use(middleware.Logger())
	e.POST("/product", AddProduct)

	e.POST("/file", Addfile)
	e.GET("/file/:file_name", GetFile)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":8080"))
}
