// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package simplesql

import (
	"time"
)

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
